
#include "../header/func.h"

// Func Constructor
Func::Func()
{
    this->content = "";
    this->returnType = "";
    this->name = "";
}

// Adds function details like name and return type
void Func::addDetails(vector<Token> funcDetails)
{
    for (Token token : funcDetails)
    {
        if (token.token == DATATYPE)
            this->returnType = token.value;
        else if (token.token == IDEN)
            this->name = token.value;
    }
}

// Uses assembly code generated by the statements within the function
void Func::addContent(string content)
{
    this->content = content;
}

// Returns assembly code for function
string Func::print()
{
    return name + " proc:\n\n" 
            + content + 
            "\nret 0;\n";
}