
#include "../header/func.h"

// Func Constructor
Func::Func()
{
    this->content = "";
    this->returnType = "";
    this->name = "";
}

// Adds function details like name and return type
void Func::addDetails(Token* funcDetail)
{
    if (funcDetail->token == DATATYPE)
        this->returnType = funcDetail->value;
    else if (funcDetail->token == IDEN)
        this->name = funcDetail->value;
}

// Uses assembly code generated by the statements within the function
void Func::addContent(string content)
{
    this->content = content;
}

// Returns assembly code for function
string Func::print()
{
    return name + " proc:\n\n";
}